### PR TITLE
fix: footer on mobile

### PR DESCRIPTION
**Pull request by Nebulis**

### CODE REVIEW

**Comment by Nebulis** [comment]
@witxhhaven please helpppp

**Comment by witxhhaven** [comment]
image

thought the contact column should be at the side instead of bottom

**Comment by witxhhaven** [comment]
image

you showed me this yesterday

**Comment by witxhhaven** [comment]
i have added a fix for desktop to display side by side  
@barrylim @Nebulis .. have a look at staging before approving

**Review by barrylim — APPROVED** [review]

**Pull request merged**
